version: '3'

services:
  laboratorio:
    build: laboratorio
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://18.191.54.170:3306/laboratoriodb?createDatabaseIfNotExist=true&serverTimezone=UTC
      USER_DB: root
      PASSWORD_DB: roottoor
    restart: always
    depends_on:
      laboratorio_host:
          condition: service_healthy
  laboratorio_host:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: roottoor
      MYSQL_PASSWORD: roottoor
      MYSQL_DATABASE: laboratoriodb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
