version: '3.8'
services:
  laboratorio-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      USER_DB: root
      PASSWORD_DB: roottoor
    restart: unless-stopped